# Generated by Django 3.2.7 on 2023-01-08 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exampleproject', '0003_auto_20230108_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='semester',
            name='branches',
            field=models.ManyToManyField(to='exampleproject.branch'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='curriculum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exampleproject.classproject'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='units',
            field=models.ManyToManyField(to='exampleproject.unit'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='topic',
            field=models.ManyToManyField(to='exampleproject.topic'),
        ),
    ]
